name: CI
on: [push, pull_request]
jobs:

  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v
      working-directory: internal/gossip

    - name: Build to Linux
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.ref_type == 'tag'
      run: go build
      working-directory: cmd/gossip

    - name: Build to Win64
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.ref_type == 'tag'
      run: go build -o gossip64.exe
      working-directory: cmd/gossip
      env:
        GOOS: Windows
        GOARCH: amd64

    - name: Build to Win32
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.ref_type == 'tag'
      run: go build -o gossip32.exe
      working-directory: cmd/gossip
      env:
        GOOS: Windows
        GOARCH: "386"

  