name: Push and pull-request project

on: 
  push:
    tags-ignore:
      - "v*"
  pull_request:

jobs:
  test-and-build:
    name: Test project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [Linux, Windows]
        goarch: [386, amd64]

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
        working-directory: internal/gossip
      - name: Build
        run: go build -ldflags "-X main.revision=$(REVISION)" -o gossip_${GOOS}_${GOARCH}
        working-directory: cmd/gossip
        env:
          GOOS: ${{matrix.goos}}
          GOARCH: ${{matrix.goarch}}
          REVISION: ${{github.ref_name}}
